In [10]:
# Import necessary libraries
import pandas as pd
import numpy as np

import keras
from keras.layers import Dense
from keras.models import Sequential

**Dataset Link : https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv**

In [2]:
# Load, read, and print data
path = "C:/Users/shakib/Downloads/concrete_data.csv"
data = pd.read_csv(path)
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
# Number of rows and columns
data.shape

(1030, 9)

In [4]:
# Summary of the dataset
data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
# Number of missing values
data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
# Split data in predictors and target
predictors = data.drop(columns=['Strength'])
target = data.Strength

In [7]:
# Normalization (Manual)
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
# Number of predictors
n_cols = predictors_norm.shape[1]

# Build Neural Network

In [12]:
# Define regression model
def regression_model():
    model = Sequential()
    model.add(Dense(50, activation='relu', input_shape=(n_cols, )))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # Compile the model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# Train and Test the Network

In [13]:
# Build the model
model = regression_model()

In [14]:
# Fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 3s - loss: 1613.8960 - val_loss: 1104.8536
Epoch 2/100
23/23 - 0s - loss: 1454.0292 - val_loss: 953.3568
Epoch 3/100
23/23 - 0s - loss: 1197.8717 - val_loss: 736.6716
Epoch 4/100
23/23 - 0s - loss: 843.8078 - val_loss: 496.8978
Epoch 5/100
23/23 - 0s - loss: 498.5443 - val_loss: 319.6566
Epoch 6/100
23/23 - 0s - loss: 305.4271 - val_loss: 246.7594
Epoch 7/100
23/23 - 0s - loss: 247.2308 - val_loss: 220.2843
Epoch 8/100
23/23 - 0s - loss: 228.7267 - val_loss: 207.7581
Epoch 9/100
23/23 - 0s - loss: 215.6126 - val_loss: 199.8313
Epoch 10/100
23/23 - 0s - loss: 205.4592 - val_loss: 193.5984
Epoch 11/100
23/23 - 0s - loss: 196.8975 - val_loss: 187.5600
Epoch 12/100
23/23 - 0s - loss: 190.0940 - val_loss: 183.9482
Epoch 13/100
23/23 - 0s - loss: 183.6180 - val_loss: 179.4545
Epoch 14/100
23/23 - 0s - loss: 179.3194 - val_loss: 179.1967
Epoch 15/100
23/23 - 0s - loss: 174.5080 - val_loss: 175.1832
Epoch 16/100
23/23 - 0s - loss: 170.5607 - val_loss: 175.3118
Epoch 17/100
23/23 - 0s - loss: 167.0076 - val_loss: 172.4375
Epoch 18/100
23/23 - 0s - loss: 163.6525 - val_loss: 173.6075
Epoch 19/100
23/23 - 0s - loss: 160.4773 - val_loss: 173.2107
Epoch 20/100
23/23 - 0s - loss: 158.1564 - val_loss: 176.0065
Epoch 21/100
23/23 - 0s - loss: 155.5696 - val_loss: 173.8121
Epoch 22/100
23/23 - 0s - loss: 153.1613 - val_loss: 174.1916
Epoch 23/100
23/23 - 0s - loss: 151.6063 - val_loss: 172.5668
Epoch 24/100
23/23 - 0s - loss: 149.6682 - val_loss: 176.0169
Epoch 25/100
23/23 - 0s - loss: 148.2157 - val_loss: 172.9862
Epoch 26/100
23/23 - 0s - loss: 146.6976 - val_loss: 176.0285
Epoch 27/100
23/23 - 0s - loss: 145.2067 - val_loss: 177.2432
Epoch 28/100
23/23 - 0s - loss: 143.6340 - val_loss: 178.9976
Epoch 29/100
23/23 - 0s - loss: 142.0613 - val_loss: 177.4134
Epoch 30/100
23/23 - 0s - loss: 140.8088 - val_loss: 178.9988
Epoch 31/100
23/23 - 0s - loss: 139.9418 - val_loss: 177.3895
Epoch 32/100
23/23 - 0s - loss: 138.7025 - val_loss: 181.6744
Epoch 33/100
23/23 - 0s - loss: 136.8922 - val_loss: 180.4425
Epoch 34/100
23/23 - 0s - loss: 135.7761 - val_loss: 181.0694
Epoch 35/100
23/23 - 0s - loss: 135.1305 - val_loss: 179.3962
Epoch 36/100
23/23 - 0s - loss: 133.3478 - val_loss: 180.1171
Epoch 37/100
23/23 - 0s - loss: 131.4623 - val_loss: 180.0775
Epoch 38/100
23/23 - 0s - loss: 130.3340 - val_loss: 180.9760
Epoch 39/100
23/23 - 0s - loss: 129.4736 - val_loss: 179.6801
Epoch 40/100
23/23 - 0s - loss: 128.5705 - val_loss: 180.3215
Epoch 41/100
23/23 - 0s - loss: 127.5730 - val_loss: 183.7912
Epoch 42/100
23/23 - 0s - loss: 125.4031 - val_loss: 178.8430
Epoch 43/100
23/23 - 0s - loss: 124.4640 - val_loss: 181.6868
Epoch 44/100
23/23 - 0s - loss: 123.5226 - val_loss: 179.5365
Epoch 45/100
23/23 - 0s - loss: 122.1469 - val_loss: 180.6122
Epoch 46/100
23/23 - 0s - loss: 121.2290 - val_loss: 177.2966
Epoch 47/100
23/23 - 0s - loss: 119.0984 - val_loss: 177.6336
Epoch 48/100
23/23 - 0s - loss: 117.6653 - val_loss: 177.2084
Epoch 49/100
23/23 - 0s - loss: 116.4170 - val_loss: 174.7236
Epoch 50/100
23/23 - 0s - loss: 114.1109 - val_loss: 176.5396
Epoch 51/100
23/23 - 0s - loss: 112.7491 - val_loss: 172.9902
Epoch 52/100
23/23 - 0s - loss: 110.6638 - val_loss: 172.9665
Epoch 53/100
23/23 - 0s - loss: 108.7460 - val_loss: 170.9947
Epoch 54/100
23/23 - 0s - loss: 106.7997 - val_loss: 170.6841
Epoch 55/100
23/23 - 0s - loss: 104.6532 - val_loss: 164.5790
Epoch 56/100
23/23 - 0s - loss: 102.6527 - val_loss: 167.7875
Epoch 57/100
23/23 - 0s - loss: 99.3821 - val_loss: 162.3760
Epoch 58/100
23/23 - 0s - loss: 96.7696 - val_loss: 162.4160
Epoch 59/100
23/23 - 0s - loss: 94.5439 - val_loss: 155.7676
Epoch 60/100
23/23 - 0s - loss: 91.9749 - val_loss: 164.5410
Epoch 61/100
23/23 - 0s - loss: 89.4867 - val_loss: 150.6800
Epoch 62/100
23/23 - 0s - loss: 87.2511 - val_loss: 156.0095
Epoch 63/100
23/23 - 0s - loss: 84.6654 - val_loss: 155.7026
Epoch 64/100
23/23 - 0s - loss: 82.1231 - val_loss: 153.8837
Epoch 65/100
23/23 - 0s - loss: 80.3057 - val_loss: 149.6083
Epoch 66/100
23/23 - 0s - loss: 78.3811 - val_loss: 149.1114
Epoch 67/100
23/23 - 0s - loss: 75.5670 - val_loss: 150.0527
Epoch 68/100
23/23 - 0s - loss: 73.8408 - val_loss: 141.6453
Epoch 69/100
23/23 - 0s - loss: 71.6612 - val_loss: 149.2022
Epoch 70/100
23/23 - 0s - loss: 70.3616 - val_loss: 140.1097
Epoch 71/100
23/23 - 0s - loss: 68.3658 - val_loss: 144.1796
Epoch 72/100
23/23 - 0s - loss: 66.5157 - val_loss: 144.0416
Epoch 73/100
23/23 - 0s - loss: 64.9511 - val_loss: 139.7695
Epoch 74/100
23/23 - 0s - loss: 63.6099 - val_loss: 139.7139
Epoch 75/100
23/23 - 0s - loss: 62.2771 - val_loss: 144.9093
Epoch 76/100
23/23 - 0s - loss: 61.0879 - val_loss: 139.0197
Epoch 77/100
23/23 - 0s - loss: 58.9941 - val_loss: 142.4217
Epoch 78/100
23/23 - 0s - loss: 57.8284 - val_loss: 138.2205
Epoch 79/100
23/23 - 0s - loss: 56.6931 - val_loss: 145.7237
Epoch 80/100
23/23 - 0s - loss: 55.2830 - val_loss: 138.0367
Epoch 81/100
23/23 - 0s - loss: 53.8709 - val_loss: 132.7241
Epoch 82/100
23/23 - 0s - loss: 52.9645 - val_loss: 140.3048
Epoch 83/100
23/23 - 0s - loss: 52.0869 - val_loss: 141.8556
Epoch 84/100
23/23 - 0s - loss: 50.8763 - val_loss: 139.9888
Epoch 85/100
23/23 - 0s - loss: 49.6451 - val_loss: 133.0945
Epoch 86/100
23/23 - 0s - loss: 48.5404 - val_loss: 133.9275
Epoch 87/100
23/23 - 0s - loss: 48.1169 - val_loss: 137.2028
Epoch 88/100
23/23 - 0s - loss: 47.0377 - val_loss: 127.9741
Epoch 89/100
23/23 - 0s - loss: 46.5064 - val_loss: 132.5204
Epoch 90/100
23/23 - 0s - loss: 45.6531 - val_loss: 146.8005
Epoch 91/100
23/23 - 0s - loss: 44.9565 - val_loss: 136.0703
Epoch 92/100
23/23 - 0s - loss: 42.4974 - val_loss: 132.0026
Epoch 93/100
23/23 - 0s - loss: 41.6998 - val_loss: 136.3081
Epoch 94/100
23/23 - 0s - loss: 40.6861 - val_loss: 125.6182
Epoch 95/100
23/23 - 0s - loss: 39.5827 - val_loss: 136.1696
Epoch 96/100
23/23 - 0s - loss: 39.2792 - val_loss: 126.1205
Epoch 97/100
23/23 - 0s - loss: 38.6631 - val_loss: 128.7939
Epoch 98/100
23/23 - 0s - loss: 37.9781 - val_loss: 126.3933
Epoch 99/100
23/23 - 0s - loss: 38.1083 - val_loss: 133.1519
Epoch 100/100
23/23 - 0s - loss: 36.4864 - val_loss: 125.8155